### ISSUE TITLE
Ignore `one_member_abstracts` rule

### ISSUE THREAD

**Issue by RaphaelOliveiraMoura** [olmps/memo#29]
At dart standards is recommended not use abstract classes with just one method, but for some cases I think is more readable and scalable use abstract classes with just one member, like this:

```dart
abstract class DeckRepository {
  Future<List<Deck>> getAllDecks();
}
```

https://dart-lang.github.io/linter/lints/one_member_abstracts.html

This is a point that impact the ci because we are running `flutter analyse` that check the style rules of project. 

So we can do two things:
1) Disable this rule at dart rules on `analysis_options.yaml` file like this:

```yaml
include: package:strict/analysis_options.yaml

linter:
  rules:
    one_member_abstracts: false

``` 

2) Update all places that we use abstract classes with one member like this:

![image](https://user-images.githubusercontent.com/41276009/113732706-2f8bff00-96d0-11eb-8e9f-330a5ec703b9.png)
